import os

import numpy as np

import src.config as cfg
from src.inference.models import BaseModel
from src.inference.onnx import make_session


class YamnetMediumGeneralOnnx(BaseModel):
    """ONNX build of yamnet_medium_general. Generated by tools/onnxify_model.py."""

    modelname = "yamnet_medium_general_onnx"
    embeddername = 'yamnet_onnx'
    digits_results = 8

    def initialize(self):
        self.embedder.processor = self.processor
        self.embedder.initialize()
        dir_model = os.path.abspath(os.path.join(cfg.DIR_MODELS, self.modelname))
        self.model = make_session(os.path.join(dir_model, 'model.onnx'), self.processor)
        self.name_in = self.model.get_inputs()[0].name

    def predict(self, audiosamples):
        return self.predict_embeddings(self.embedder.embed(audiosamples))

    def predict_embeddings(self, embeddings):
        embeddings = np.asarray(embeddings, dtype=np.float32)
        return self.model.run(None, {self.name_in: embeddings})[0]
