"""Create an ONNX sibling of a trained buzzdetect model.

    .venv/bin/python3 tools/onnxify_model.py yamnet_medium_general

Reads models/<name>/ and writes models/<name>_onnx/ containing model.onnx, a
model.py that runs it through onnxruntime, and a copy of config_model.json
pointed at the ONNX embedder. The original model directory is left untouched:
the ONNX model is an additional model, selectable by name, not a replacement.

Requires TensorFlow (to read model.keras) and so is a build-time tool; nothing
in the resulting model directory imports TensorFlow.
"""

import argparse
import json
import os
import shutil
import sys

import numpy as np

sys.path.insert(0, os.getcwd())

import keras
import onnxruntime as ort

# Loose enough for float32 reassociation between two runtimes, tight enough to
# catch a mis-exported graph.
TOL = 1e-4

TEMPLATE_MODEL_PY = '''import os

import numpy as np
import onnxruntime as ort

import src.config as cfg
from src.inference.models import BaseModel


class {classname}(BaseModel):
    """ONNX build of {source}. Generated by tools/onnxify_model.py."""

    modelname = "{modelname}"
    embeddername = '{embeddername}'
    digits_results = {digits_results}

    def initialize(self):
        self.embedder.initialize()
        dir_model = os.path.abspath(os.path.join(cfg.DIR_MODELS, self.modelname))
        self.model = ort.InferenceSession(
            os.path.join(dir_model, 'model.onnx'),
            providers=['CPUExecutionProvider'])
        self.name_in = self.model.get_inputs()[0].name

    def predict(self, audiosamples):
        return self.predict_embeddings(self.embedder.embed(audiosamples))

    def predict_embeddings(self, embeddings):
        embeddings = np.asarray(embeddings, dtype=np.float32)
        return self.model.run(None, {{self.name_in: embeddings}})[0]
'''


def classname_for(modelname):
    return ''.join(part.capitalize() for part in modelname.split('_'))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('modelname', help='name of the model directory under models/')
    parser.add_argument('--embeddername', default='yamnet_onnx',
                        help='ONNX embedder the new model should use')
    parser.add_argument('--dir_models', default='models')
    args = parser.parse_args()

    dir_src = os.path.join(args.dir_models, args.modelname)
    name_out = f'{args.modelname}_onnx'
    dir_out = os.path.join(args.dir_models, name_out)

    if not os.path.isdir(dir_src):
        raise SystemExit(f'no such model directory: {dir_src}')

    with open(os.path.join(dir_src, 'config_model.json')) as f:
        config = json.load(f)

    os.makedirs(dir_out, exist_ok=True)

    print(f'loading {dir_src}/model.keras')
    model = keras.saving.load_model(os.path.join(dir_src, 'model.keras'),
                                    compile=False)
    n_embeddings = model.inputs[0].shape[-1] if model.inputs else 1024
    # Keras refuses to export a model it has never seen called.
    probe = np.zeros((1, n_embeddings), dtype=np.float32)
    model(probe)

    path_onnx = os.path.join(dir_out, 'model.onnx')
    print(f'exporting {path_onnx}')
    model.export(path_onnx, format='onnx', verbose=False)

    session = ort.InferenceSession(path_onnx, providers=['CPUExecutionProvider'])
    name_in = session.get_inputs()[0].name
    print(f'  {os.path.getsize(path_onnx) / 1e6:.2f} MB, '
          f'input {session.get_inputs()[0].shape}, '
          f'output {session.get_outputs()[0].shape}')

    print('checking parity against the keras model')
    rng = np.random.default_rng(0)
    worst = 0.0
    for n_frames in (1, 8, 512):
        embeddings = rng.standard_normal((n_frames, n_embeddings)).astype(np.float32)
        expected = np.asarray(model(embeddings))
        got = session.run(None, {name_in: embeddings})[0]
        if expected.shape != got.shape:
            raise SystemExit(f'shape mismatch: keras {expected.shape} vs onnx {got.shape}')
        d = float(np.abs(expected - got).max())
        worst = max(worst, d)
        print(f'  n_frames={n_frames:<5} max|d|={d:.2e}')
    if worst > TOL:
        raise SystemExit(f'parity check FAILED: {worst:.2e} > {TOL}')

    config['embeddername'] = args.embeddername
    with open(os.path.join(dir_out, 'config_model.json'), 'w') as f:
        json.dump(config, f)

    with open(os.path.join(dir_out, 'model.py'), 'w') as f:
        f.write(TEMPLATE_MODEL_PY.format(
            classname=classname_for(name_out),
            source=args.modelname,
            modelname=name_out,
            embeddername=args.embeddername,
            digits_results=config.get('digits_results', 8),
        ))

    # Carried for reference by whoever reads the results, not by the pipeline.
    for extra in ('translation.csv', 'weights.csv'):
        path_extra = os.path.join(dir_src, extra)
        if os.path.exists(path_extra):
            shutil.copy2(path_extra, os.path.join(dir_out, extra))

    print(f'parity OK: {worst:.2e}')
    print(f'wrote {dir_out}')


if __name__ == '__main__':
    main()
