name: buzzdetect-py39
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=23.2.1
  - pip:
    - tensorflow==2.13
    - pydub==0.25.1
    - tensorflow_hub==0.14.0
    - tensorflow-io==0.34.0
