import importlib.util
import json
import os
from pathlib import Path

import numpy as np

from src import config as cfg


class OnnxModel:
    """A buzzdetect model: one ONNX graph, waveform in, predictions out.

    Everything the model does is in `model.onnx` -- the log-mel front end, the
    embedding trunk and the classifier head, exported and fused into a single
    graph by buzzdetect-training's `tools/export_onnx.py`. There is no embedder
    plugin and no TensorFlow; a model directory is `model.onnx`, a
    `config_model.json` naming the classes, and a `model.py` that is nothing
    but the class attributes below.

    Subclasses declare, and are generated by the export tool:

      samplerate, framelength_s, digits_time   what the front end expects, and
                                               what the writer needs to turn
                                               frames into timestamps
      digits_results                           rounding for the result columns
      samples_hop, samples_min                 the graph's framing rule; see
                                               n_frames()

    The session is built at one fixed input length (`samples_session`), which
    the analyzer sets from the chunk length before initialize(). That is not a
    tuning choice: CoreML's MLProgram format cannot compile a graph with an
    unbounded dimension, so a dynamic session simply fails to run on macOS.
    predict() zero-pads each chunk up to that length and returns only the
    frames the real audio covers.
    """

    modelname: str = None
    samplerate: int = None
    framelength_s: float = None
    digits_time: int = None
    digits_results: int = None
    # Samples between the start of one frame and the next.
    samples_hop: int = None
    # The fewest samples that produce a frame -- shorter input is padded up to
    # it. Larger than samples_hop, because the front end's STFT window overhangs
    # the frame it belongs to.
    samples_min: int = None

    def __init__(self, framehop_prop):
        # The patch hop is welded to the patch window inside the exported
        # graph, so an overlapping framehop cannot be honoured. Refuse it
        # rather than silently analysing on contiguous frames.
        if framehop_prop != 1:
            raise ValueError(
                f'{self.modelname} only supports framehop_prop=1, got '
                f'{framehop_prop}. Overlapping frames would have to be a '
                f'parameter of the exported graph, and are not.')
        self.framehop_prop = framehop_prop
        self.framehop_s = self.framelength_s * framehop_prop

        self.model = None
        # Both set by WorkerInferer before initialize().
        self.processor = 'CPU'
        self.samples_session = None

        with open(os.path.join(cfg.DIR_MODELS, self.modelname,
                               'config_model.json')) as f:
            self.config = json.load(f)

    def session_length(self, chunklength_s):
        """Samples to build the session for, given the analyzer's chunk length.

        One frame longer than the chunk needs. Resampling a chunk to the
        model's rate does not always land on exactly the expected sample count,
        and a chunk that came back a few samples long would otherwise not fit
        the session it was sized for. The spare frame costs one frame of
        compute per chunk and removes the whole class of problem.
        """
        n_chunk = int(round(chunklength_s * self.samplerate))
        return self.samples_min + self.samples_hop * self.n_frames(n_chunk)

    def n_frames(self, n_samples):
        """How many frames the graph returns for n_samples of audio.

        Two things here are not what they look like.

        The first frame needs more samples than the hop -- the front end pads
        up to a whole patch plus the STFT window's overhang -- so this is not
        ceil(n_samples / samples_hop).

        And the hop division is a float32 multiply by the reciprocal of the
        hop, not a division. tf2onnx emits it that way, and it matters: 1/15360
        is not exact in float32, so at some exact multiples of the hop the
        quotient lands just above the integer and the ceil returns one more
        frame than real arithmetic would. 61680 samples and 3210480 samples are
        two such lengths. Doing this in float64 is wrong by one frame there,
        which would silently drop a frame of audio off the end of a chunk.

        buzzdetect-training's export tool checks this against the graph at
        every exact multiple of the hop before it ships a model.
        """
        if n_samples <= 0:
            return 0
        after = np.float32(max(0, n_samples - self.samples_min))
        reciprocal = np.float32(1.0) / np.float32(self.samples_hop)
        return 1 + int(np.ceil(after * reciprocal))

    def initialize(self):
        from src.inference.onnx import make_session

        if self.samples_session is None:
            raise RuntimeError(
                f'{self.modelname}.samples_session was not set before '
                f'initialize(); the session needs a fixed input length.')
        path = os.path.join(os.path.abspath(cfg.DIR_MODELS), self.modelname,
                            'model.onnx')
        self.model = make_session(path, self.processor, self.samples_session)
        self.name_in = self.model.get_inputs()[0].name

    def predict(self, audiosamples):
        """Predictions for one chunk of audio at self.samplerate.

        The chunk is padded up to the session's length and the surplus frames
        are dropped here, so nothing downstream ever sees a result computed
        from padding.
        """
        samples = np.asarray(audiosamples, dtype=np.float32)
        n = samples.shape[0]
        if n > self.samples_session:
            raise ValueError(
                f'{self.modelname} got a {n}-sample chunk but its session is '
                f'built for {self.samples_session}. The analyzer sizes the '
                f'session from chunklength; a chunk longer than that should '
                f'not exist.')

        padded = np.zeros(self.samples_session, dtype=np.float32)
        padded[:n] = samples
        results = self.model.run(None, {self.name_in: padded})[0]
        return results[:self.n_frames(n)]


def load_model(modelname: str, framehop_prop: float, initialize: bool):
    """Load a model by name from its directory's model.py.

    Each model directory holds a model.py defining one OnnxModel subclass,
    alongside the model.onnx it names.
    """
    model_path = Path(cfg.DIR_MODELS) / modelname

    if not model_path.exists():
        raise ValueError(f"model '{modelname}' not found in {cfg.DIR_MODELS}")

    spec = importlib.util.spec_from_file_location(
        f"{modelname}_model",
        model_path / "model.py"
    )
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
    except ImportError as e:
        # Model directories built before the front end moved into the graph
        # import a base class that no longer exists, and their model.onnx is
        # the classifier head alone. Nothing here can run them.
        raise RuntimeError(
            f"{modelname} was built for the old two-part runtime, where an "
            f"embedder plugin fed a classifier head. Re-export it with "
            f"buzzdetect-training's tools/export_onnx.py, which now writes one "
            f"graph that takes a waveform.") from e

    # Match on where the class was defined rather than just on what it
    # subclasses: model.py imports OnnxModel to subclass it, and dir() is
    # alphabetical, so the import would otherwise win over the class the file
    # exists to define.
    model_class = None
    for item_name in dir(module):
        item = getattr(module, item_name)
        if (isinstance(item, type) and
                issubclass(item, OnnxModel) and
                item.__module__ == module.__name__):
            model_class = item
            break

    if model_class is None:
        raise ValueError(f"No OnnxModel subclass defined in {modelname}/model.py")

    model = model_class(framehop_prop=framehop_prop)

    if initialize:
        model.initialize()

    return model
