from src.inference.models import OnnxModel


class ModelGeneralV3(OnnxModel):
    """Generated by buzzdetect-training tools/export_onnx.py. Do not edit.

    model.onnx is the whole model: waveform in, predictions out. The front end
    that used to live in an embedder plugin is inside the graph.
    """

    modelname = "model_general_v3"
    samplerate = 16000
    framelength_s = 0.96
    digits_time = 2
    digits_results = 2
    samples_hop = 15360
    samples_min = 15600
